[package]
name = "fisher_yates_shuffle"
version = "0.1.0"
authors = ["coderve <shreyansh.rastogi76@gmail.com>"]
edition = "2018"

[dependencies]
rand = { git = "https://github.com/rust-lang-nursery/rand.git" }
